DEV: sync paks

diff --git a/paks/assist/configure b/paks/assist/configure
--- a/paks/assist/configure
+++ b/paks/assist/configure
@@ -1,28 +1,48 @@
 #!/bin/bash
 #
-#   configure - used by farm.json for node applications
+#   configure - Configure a product
+#
+#   Usage: PARTS="parts" GPG_PASSWORD="password" configure ..
+#
+#   Manages git-crypt files, submodules and parts
 #
 
-if [ -f package.json ] ; then
-    echo 'yarn install ...'
-    output=$(yarn install --silent --mutex file:/tmp/.yarn-mutex 2>&1)
-    if [ $? = 0 ] ; then
-        echo ${output} | perl -pe 's/\e([^\[\]]|\[.*?[a-zA-Z]|\].*?\a)//g' | egrep -v 'Waiting for the other'
+GPG_PASSFILE=/etc/farm/gpg.key
+
+PARTS=$(echo ${PARTS} | tr ',' ' ')
+
+#
+#   Decrypt secrets
+#
+if [ -x ".git-crypt" -a ! -f .decrypted ] ; then
+    echo "Decrypt secrets"
+    if [ -z "${GPG_PASSWORD}" -a -f ${GPG_PASSFILE} ] ; then
+        GPG_PASSWORD=$(cat ${GPG_PASSFILE})
+    fi
+    if [ "${GPG_PASSWORD}" != "" ] ; then
+        gpg --pinentry-mode loopback --no-tty --passphrase "${GPG_PASSWORD}" --yes \
+            --output .git-crypt/keys/default/0/decrypted.key \
+            --decrypt .git-crypt/keys/default/0/*.gpg
+        git-crypt unlock .git-crypt/keys/default/0/decrypted.key
     else
-        echo "Yarn failed"
-        echo ${output}
+        git-crypt unlock
+    fi
+    if [ $? != 0 ] ; then
+        echo "Git unlock failed"
         exit 1
     fi
+    >.decrypted
 fi
 
-if [ -f typings.json ] ; then
-    echo 'typings install ...'
-    output=$(typings install >/dev/null 2>&1)
-    if [ $? = 0 ] ; then
-        echo ${output} | grep -v deprecated
-    else
-        echo "Typings failed"
-        echo ${output}
-        exit 1
+git submodule update --init --recursive
+
+for PART in ${PARTS}
+do
+    cd ./${PART}
+    if [ -f configure ] ; then
+        echo -e "\nConfigure ${PART}"
+        PART=${PART} ./configure $*
     fi
-fi
+    [ $? != 0 ] && exit 2
+    cd ..
+done
